export const usCities = [
  "007",
  "019",
  "023",
  "037",
  "039",
  "047",
  "051",
  "077",
  "ABBEVILLE",
  "Aberdeen",
  "ADA",
  "ADAIR",
  "ADAMS",
  "Adrian",
  "Akron",
  "ALAMEDA",
  "Albany",
  "Albany-Lebanon",
  "Albany-Schenectady-Troy",
  "Albuquerque",
  "ALEXANDER",
  "Allegan",
  "ALLEGANY",
  "Allentown-Bethlehem-Easton",
  "Altoona",
  "AMADOR",
  "Amarillo",
  "Americus",
  "Ames",
  "Anchorage",
  "ANCHORAGE",
  "Anderson",
  "ANDERSON",
  "ANDREW",
  "Ann Arbor",
  "ANNE ARUNDEL",
  "Appleton",
  "ARAPAHOE",
  "ARCHULETA",
  "Ardmore",
  "Arkadelphia",
  "AROOSTOOK",
  "Asheville",
  "ASHLAND",
  "Ashtabula",
  "ASOTIN",
  "Athens",
  "Athens-Clarke County",
  "Atlanta",
  "Atlanta-Sandy Springs-Marietta",
  "Atlantic City",
  "Augusta-Richmond County",
  "Augusta-Waterville",
  "Austin-Round Rock",
  "AVERY",
  "BAKER",
  "Bakersfield",
  "BALTIMORE",
  "Baltimore-Towson",
  "Bangor",
  "BANNOCK",
  "Baraboo",
  "Barnstable Town",
  "BARTHOLOMEW",
  "BASTROP",
  "Baton Rouge",
  "BAYAMON",
  "Bay City",
  "BEAUFORT",
  "Beaumont-Port Arthur",
  "BECKER",
  "Bellingham",
  "BELMONT",
  "BELTRAMI",
  "Bend",
  "BENEWAH",
  "Bennington",
  "BERKELEY",
  "BERKS",
  "BERKSHIRE",
  "Berlin",
  "BERNALILLO",
  "BETHEL",
  "BIG HORN",
  "Billings",
  "Birmingham-Hoover",
  "Bishop",
  "Blacksburg-Christiansburg-Radford",
  "BLAINE",
  "Bloomington",
  "Bloomington-Normal",
  "BOISE",
  "Boise City-Nampa",
  "BOLIVAR",
  "BONNER",
  "Boston-Cambridge-Quincy",
  "Boulder",
  "BOULDER",
  "BOUNDARY",
  "Bowling Green",
  "BRADFORD",
  "Brainerd",
  "BREWSTER",
  "Bridgeport-Stamford-Norwalk",
  "Brigham City",
  "BRISTOL",
  "BROOKINGS",
  "BROWARD",
  "BROWN",
  "Brownsville-Harlingen",
  "Brunswick",
  "BRUNSWICK",
  "BRYAN",
  "Buffalo-Niagara Falls",
  "Burlington-South Burlington",
  "BUTLER",
  "BUTTE",
  "CA8 - ARB",
  "CABELL",
  "CACHE",
  "CADDO",
  "Cadillac",
  "CALAVERAS",
  "Cambridge",
  "CAMERON",
  "Canton-Massillon",
  "Cape Coral-Fort Myers",
  "CARBON",
  "CARIBOU",
  "Carlsbad-Artesia",
  "CARLTON",
  "CARSON CITY",
  "CARTER",
  "CASCADE",
  "Casper",
  "CASS",
  "CASWELL",
  "CATANO",
  "CEDAR",
  "Cedar Rapids",
  "Chambersburg",
  "CHAMPAIGN",
  "Champaign-Urbana",
  "CHARLESTON",
  "Charleston-North Charleston",
  "Charlotte-Gastonia-Concord",
  "Charlottesville",
  "Chattanooga",
  "CHAUTAUQUA",
  "CHELAN",
  "CHESTERFIELD",
  "Cheyenne",
  "Chicago-Naperville-Joliet",
  "Chico",
  "CHIHUAHUA STATE",
  "CHURCHILL",
  "Cincinnati-Middletown",
  "City of The Dalles",
  "CLACKAMAS",
  "CLAIBORNE",
  "CLALLAM",
  "CLARK",
  "Clarksville",
  "Cleveland",
  "Cleveland-Elyria-Mentor",
  "Clinton",
  "CLINTON",
  "COCONINO",
  "CODINGTON",
  "Coeur d'Alene",
  "Colorado Springs",
  "Columbia",
  "COLUMBIA",
  "Columbus",
  "COLUSA",
  "Concord",
  "CONVERSE",
  "COOK",
  "Cookeville",
  "COOS",
  "Corning",
  "Corpus Christi",
  "Corsicana",
  "Corvallis",
  "COTTON",
  "CUMBERLAND",
  "CURRY",
  "CUSTER",
  "CUYAHOGA",
  "DAKOTA",
  "Dallas-Fort Worth-Arlington",
  "Dalton",
  "Daphne-Fairhope",
  "Davenport-Moline-Rock Island",
  "Dayton",
  "Decatur",
  "DE KALB",
  "DELAWARE",
  "DEL NORTE",
  "DELTA",
  "Deltona-Daytona Beach-Ormond Beach",
  "Deming",
  "DENVER",
  "Denver-Aurora",
  "DESCHUTES",
  "Des Moines",
  "Detroit-Warren-Livonia",
  "DEWEY",
  "Dickinson",
  "DODGE",
  "Dodge City",
  "DONA ANA",
  "DOOR",
  "DORCHESTER",
  "DOUGLAS",
  "Dover",
  "DuBois",
  "DUCHESNE",
  "DUKES",
  "Duluth",
  "DUNN",
  "Durango",
  "Durham",
  "DUVAL",
  "Dyersburg",
  "Eagle Pass",
  "East Liverpool-Salem",
  "East Stroudsburg",
  "EAU CLAIRE",
  "EDDY",
  "Effingham",
  "El Centro",
  "El Dorado",
  "Elizabethtown",
  "Elkhart-Goshen",
  "ELKO",
  "Ellensburg",
  "El Paso",
  "Erie",
  "ERIE",
  "ESSEX",
  "Eugene-Springfield",
  "Evanston",
  "Evansville",
  "Fairbanks",
  "FAIRBANKS NORTH STAR",
  "FAIRFIELD",
  "Farmington",
  "FAYETTE",
  "Fayetteville",
  "Fayetteville-Springdale-Rogers",
  "FERGUS",
  "FLAGLER",
  "Flagstaff",
  "FLATHEAD",
  "Flint",
  "Florence",
  "Florence-Muscle Shoals",
  "Fond du Lac",
  "FOREST",
  "FORREST",
  "Fort Collins-Loveland",
  "Fort Smith",
  "Fort Walton Beach-Crestview-Destin",
  "Fort Wayne",
  "FRA",
  "FRANKLIN",
  "Fresno",
  "FRESNO",
  "FS1 - Forest Service",
  "Gadsden",
  "Gainesville",
  "GALLATIN",
  "GALLIA",
  "GARFIELD",
  "GARRETT",
  "GBU",
  "Georgetown",
  "Gettysburg",
  "GILA",
  "GILES",
  "Gillette",
  "GILMER",
  "GILPIN",
  "GLENN",
  "GOSHEN",
  "GRADY",
  "GRAHAM",
  "Granbury",
  "Grand Island",
  "Grand Junction",
  "Grand Rapids-Wyoming",
  "GRANT",
  "Grants Pass",
  "GRANVILLE",
  "Greeley",
  "Green Bay",
  "GREENBRIER",
  "GREENE",
  "Greensboro-High Point",
  "Greenville",
  "Gulfport-Biloxi",
  "GUNNISON",
  "Hagerstown-Martinsburg",
  "HAMILTON",
  "HAMPDEN",
  "HANCOCK",
  "Hanford-Corcoran",
  "HARNEY",
  "Harriman",
  "HARRIS",
  "Harrisburg-Carlisle",
  "Harrison",
  "Harrisonburg",
  "HARTFORD",
  "Hartford-West Hartford-East Hartford",
  "Hattiesburg",
  "HAWAII",
  "HAYWOOD",
  "Helena",
  "HENNEPIN",
  "Hickory-Lenoir-Morganton",
  "HILLSBOROUGH",
  "Hilo",
  "HINDS",
  "Hobbs",
  "Holland-Grand Haven",
  "HOLMES",
  "Homosassa Springs",
  "Honolulu",
  "HOOD RIVER",
  "Houma-Bayou Cane-Thibodaux",
  "Houston",
  "Houston-Sugar Land-Baytown",
  "HOWARD",
  "HUGHES",
  "HUMBOLDT",
  "Huntington",
  "Huntington-Ashland",
  "Huntsville",
  "HURON",
  "IDAHO",
  "Idaho Falls",
  "Indiana",
  "Indianapolis",
  "INYO",
  "Iowa City",
  "IRON",
  "ISLAND",
  "Ithaca",
  "Jackson",
  "JACKSON",
  "Jacksonville",
  "JEFFERSON",
  "Jefferson City",
  "JEROME",
  "JERSEY",
  "JO DAVIESS",
  "JOHNSON",
  "JOHNSTON",
  "Johnstown",
  "Joplin",
  "JOSEPHINE",
  "JUNEAU",
  "Kahului-Wailuku",
  "Kalamazoo-Portage",
  "Kalispell",
  "KANAWHA",
  "Kansas City",
  "KAY",
  "Keene",
  "Kennewick-Richland-Pasco",
  "KENOSHA",
  "KENT",
  "KERN",
  "Killeen-Temple-Fort Hood",
  "KING",
  "KINGS",
  "Kingsport-Bristol-Bristol",
  "Kingsville",
  "Kinston",
  "KITSAP",
  "KLAMATH",
  "Klamath Falls",
  "KLICKITAT",
  "KNOX",
  "Knoxville",
  "Kokomo",
  "KOOTENAI",
  "Laconia",
  "La Crosse",
  "Lafayette",
  "La Grande",
  "LAKE",
  "Lake Charles",
  "Lake City",
  "Lake Havasu City-Kingman",
  "Lakeland",
  "Lancaster",
  "LANCASTER",
  "Lansing-East Lansing",
  "LA PAZ",
  "Laramie",
  "Laredo",
  "LARIMER",
  "Las Cruces",
  "Las Vegas-Paradise",
  "LATAH",
  "LAWRENCE",
  "Lawrenceburg",
  "Lawton",
  "Lebanon",
  "LEBANON",
  "LEE",
  "LEMHI",
  "LEWIS",
  "LEWIS AND CLARK",
  "Lewiston",
  "Lewiston-Auburn",
  "Lexington-Fayette",
  "LIBERTY",
  "LICKING",
  "Lima",
  "Lincoln",
  "LINCOLN",
  "Lincolnton",
  "LINN",
  "Little Rock-North Little Rock",
  "Longview",
  "LOS ANGELES",
  "Los Angeles-Long Beach-Santa Ana",
  "Louisville",
  "Lubbock",
  "LYCOMING",
  "LYON",
  "Macon",
  "MACON",
  "Madera",
  "Madison",
  "MADISON",
  "MALHEUR",
  "Malone",
  "Mammoth Cave NP",
  "MANATEE",
  "Manchester-Nashua",
  "MANISTEE",
  "Manitowoc",
  "MARICOPA",
  "MARION",
  "MARIPOSA",
  "Marshall",
  "MARTIN",
  "MASON",
  "MATANUSKA-SUSITNA",
  "MAUI",
  "MAYAGUEZ",
  "MAYES",
  "McAlester",
  "McAllen-Edinburg-Mission",
  "Medford",
  "MEIGS",
  "Memphis",
  "MENDOCINO",
  "Merced",
  "Meridian",
  "MERRIMACK",
  "Miami",
  "MIAMI - DADE",
  "Miami-Fort Lauderdale-Miami Beach",
  "Michigan City-La Porte",
  "Middlesborough",
  "MIDDLESEX",
  "MILLE LACS",
  "MILWAUKEE",
  "Milwaukee-Waukesha-West Allis",
  "MINERAL",
  "MINIDOKA",
  "Minneapolis-St. Paul-Bloomington",
  "MINNEHAHA",
  "MISSOULA",
  "MITCHELL",
  "Mobile",
  "Modesto",
  "MOFFAT",
  "MONO",
  "Monroe",
  "MONROE",
  "MONTEREY",
  "MONTEZUMA",
  "Montgomery",
  "MONTGOMERY",
  "MONTROSE",
  "Morehead City",
  "MORGAN",
  "Morgantown",
  "Morristown",
  "Moscow",
  "Moses Lake",
  "Mount Vernon",
  "Mount Vernon-Anacortes",
  "MT1",
  "MULTNOMAH",
  "Muncie",
  "Muscatine",
  "MUSCATINE",
  "Muskegon-Norton Shores",
  "Muskogee",
  "Myrtle Beach-Conway-North Myrtle Beach",
  "N/A",
  "Napa",
  "Naples-Marco Island",
  "Nashville-Davidson--Murfreesboro",
  "NASSAU",
  "NAVAJO",
  "NC1",
  "NEOSHO",
  "New Castle",
  "NEW CASTLE",
  "New Haven-Milford",
  "New Orleans-Metairie-Kenner",
  "NEW YORK",
  "New York-Northern New Jersey-Long Island",
  "NEZ PERCE",
  "Niles-Benton Harbor",
  "NOBLE",
  "Nogales",
  "NORFOLK",
  "NORTHAMPTON",
  "Norwich-New London",
  "NOWATA",
  "NPS",
  "NYE",
  "Ocala",
  "Odessa",
  "Ogden-Clearfield",
  "OKANOGAN",
  "Oklahoma City",
  "Olympia",
  "Omaha-Council Bluffs",
  "ONEIDA",
  "ORANGE",
  "Orlando-Kissimmee",
  "OTTAWA",
  "OUTAGAMIE",
  "Owensboro",
  "OXFORD",
  "Oxnard-Thousand Oaks-Ventura",
  "PACIFIC",
  "Paducah",
  "Palm Bay-Melbourne-Titusville",
  "PALM BEACH",
  "PALO ALTO",
  "Panama City-Lynn Haven",
  "PARK",
  "Parkersburg-Marietta-Vienna",
  "Pascagoula",
  "Payson",
  "Pendleton-Hermiston",
  "PENOBSCOT",
  "Pensacola-Ferry Pass-Brent",
  "Peoria",
  "PERRY",
  "PERSON",
  "PHILADELPHIA",
  "Philadelphia-Camden-Wilmington",
  "PHILLIPS",
  "Phoenix Lake-Cedar Ridge",
  "Phoenix-Mesa-Scottsdale",
  "PICKENS",
  "PIKE",
  "PIMA",
  "PINAL",
  "PINELLAS",
  "PITKIN",
  "Pittsburgh",
  "Pittsfield",
  "PLACER",
  "PLUMAS",
  "PLYMOUTH",
  "Pocatello",
  "POLK",
  "Ponca City",
  "PONCE",
  "Port Angeles",
  "Portland-South Portland-Biddeford",
  "Portland-Vancouver-Beaverton",
  "Portsmouth",
  "Poughkeepsie-Newburgh-Middletown",
  "POWDER RIVER",
  "Prescott",
  "PRINCE EDWARD",
  "Prineville",
  "Providence-New Bedford-Fall River",
  "Provo-Orem",
  "PROXY SITE - CA - CONSTANT",
  "Pullman",
  "PUTNAM",
  "Quincy",
  "RACINE",
  "Raleigh-Cary",
  "RAMSEY",
  "RANDOLPH",
  "Rapid City",
  "RAVALLI",
  "Reading",
  "Red Bluff",
  "Redding",
  "Red Wing",
  "Reno-Sparks",
  "RICHLAND",
  "Richmond",
  "RIO ARRIBA",
  "RIO BLANCO",
  "RIVERSIDE",
  "Riverside-San Bernardino-Ontario",
  "Riverton",
  "Roanoke",
  "Rochester",
  "ROCK",
  "ROCKBRIDGE",
  "Rockford",
  "ROCKINGHAM",
  "ROCKLAND",
  "Rock Springs",
  "Rocky Mount",
  "Rome",
  "ROSEBUD",
  "Roseburg",
  "Rutland",
  "SACRAMENTO",
  "Sacramento--Arden-Arcade--Roseville",
  "Salem",
  "Salinas",
  "Salisbury",
  "SALT LAKE",
  "Salt Lake City",
  "San Antonio",
  "SAN BERNARDINO",
  "SANDERS",
  "SAN DIEGO",
  "San Diego-Carlsbad-San Marcos",
  "SANDOVAL",
  "San Francisco-Oakland-Fremont",
  "SANGAMON",
  "SAN JOAQUIN",
  "San Jose-Sunnyvale-Santa Clara",
  "SAN JUAN",
  "San Juan-Caguas-Guaynabo",
  "SAN LUIS OBISPO",
  "San Luis Obispo-Paso Robles",
  "Santa Barbara-Santa Maria",
  "SANTA CRUZ",
  "Santa Cruz-Watsonville",
  "Santa Fe",
  "Santa Rosa-Petaluma",
  "Sarasota-Bradenton-Venice",
  "Sault Ste. Marie",
  "Savannah",
  "SC0",
  "SCHOOLCRAFT",
  "SCOTT",
  "Scottsbluff",
  "SCOTTS BLUFF",
  "Scranton--Wilkes-Barre",
  "Seaford",
  "Seattle-Tacoma-Bellevue",
  "Sebring",
  "Seneca",
  "SEVIER",
  "Sevierville",
  "Seymour",
  "SHEBOYGAN",
  "Shelton",
  "Sheridan",
  "SHERIDAN",
  "SHERMAN",
  "SHOSHONE",
  "Shreveport-Bossier City",
  "Si",
  "Sierra Vista-Douglas",
  "SILVER BOW",
  "SIMPSON",
  "Sioux City",
  "SISKIYOU",
  "SKAGIT",
  "Somerset",
  "SOMERSET",
  "SONOMA",
  "SONORA",
  "South Bend-Mishawaka",
  "Spartanburg",
  "Spokane",
  "SPOKANE",
  "Springfield",
  "State College",
  "ST. BERNARD",
  "STE GENEVIEVE",
  "STEVENS",
  "St. George",
  "ST. JAMES",
  "St. Joseph",
  "St. Louis",
  "ST. LOUIS",
  "ST. LOUIS (CITY)",
  "ST. LUCIE",
  "St. Marys",
  "Stockton",
  "SUBLETTE",
  "SUFFOLK",
  "Summerville",
  "SUMTER",
  "SUSQUEHANNA",
  "SUTTER",
  "SWAIN",
  "SWEETWATER",
  "Syracuse",
  "Tahlequah",
  "Tallahassee",
  "Tampa-St. Petersburg-Clearwater",
  "TANEY",
  "Taos",
  "TAYLOR",
  "Terre Haute",
  "TETON",
  "Texarkana",
  "Thomasville-Lexington",
  "TILLAMOOK",
  "TIOGA",
  "Toledo",
  "TOOELE",
  "Topeka",
  "Torrington",
  "Traverse City",
  "TRAVIS",
  "TREGO",
  "Trenton-Ewing",
  "TRINITY",
  "Truckee-Grass Valley",
  "TUCKER",
  "Tucson",
  "TULARE",
  "Tulsa",
  "TULSA",
  "TUOLUMNE",
  "Tupelo",
  "Tuscaloosa",
  "TUSCOLA",
  "TWIN FALLS",
  "Tyler",
  "UINTAH",
  "Ukiah",
  "UNION",
  "UTAH",
  "Utica-Rome",
  "Valdosta",
  "Vallejo-Fairfield",
  "VALLEY",
  "VAN BUREN",
  "Vero Beach",
  "Victoria",
  "VILAS",
  "Vincennes",
  "Vineland-Millville-Bridgeton",
  "Virginia Beach-Norfolk-Newport News",
  "Visalia-Porterville",
  "Wabash",
  "Waco",
  "Walla Walla",
  "WALLOWA",
  "Walterboro",
  "Warner Robins",
  "WARREN",
  "WASCO",
  "Washington",
  "WASHINGTON",
  "Washington-Arlington-Alexandria",
  "Waterloo-Cedar Falls",
  "Watertown-Fort Drum",
  "Wausau",
  "WAYNE",
  "Weirton-Steubenville",
  "WELD",
  "Wenatchee",
  "WESTON",
  "WEXFORD",
  "WHATCOM",
  "Wheeling",
  "WHITE PINE",
  "Whitewater",
  "WHITLEY",
  "Wichita",
  "WILL",
  "Williamsport",
  "Willimantic",
  "Wilmington",
  "Winchester",
  "Winston-Salem",
  "Worcester",
  "WORCESTER",
  "WYOMING",
  "WYTHE",
  "Yakima",
  "YAKIMA",
  "YALOBUSHA",
  "YANCEY",
  "YELLOWSTONE",
  "YORK",
  "York-Hanover",
  "Youngstown-Warren-Boardman",
  "Yuba City",
  "YUKON-KOYUKUK",
  "Yuma"
]
